@startuml PowerAPP Class Diagram
class User {
  - id
  - name
  - email
  - password
  + login()
  + register()
}

class TrainingType {
  - name
  + getName()
}

class FitnessClass {
  - name
  - instructor
  - schedule
  - maxCapacity
  + getDisponibility()
  + reserve()
}

class Gym {
  - name
  - location
  - offeredClasses
  + addClass()
  + manageSchedule()
}

class Reserve {
  - user: User
  - class: FitnessClass
  - date
  - schedule
  + confirmReserv()
}

TrainingType "1" -- "n" FitnessClass : relates with
User "1" -- "n" Reserve : realizes
FitnessClass "1" -- "n" Reserve : has
Gym "1" -- "n" FitnessClass : offers

@enduml
