@startuml PowerAPP sequence

actor User

User -> Platform: searchClasses()
Platform -> Class: getAvailableClasses()
Class -> Platform: getInstructor()
Platform -> Instructor: getInstructorDetails()
Instructor -> Platform: getClasses()
Platform -> User: displayClasses()

User -> Platform: makeReservation(classId, userId)
Platform -> Class: getClassDetails(classId)
Class -> Platform: checkAvailability(classId)
Platform -> User: displayReservationConfirmation()

@enduml
