"""empty message

Revision ID: 08d5986c5392
Revises: 6f1e15ac89b5
Create Date: 2023-11-16 20:19:03.994353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d5986c5392'
down_revision = '6f1e15ac89b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_name_key', ['name'])

    # ### end Alembic commands ###
