"""empty message

Revision ID: 2ff9c7ad6b7a
Revises: 138d769e17da
Create Date: 2023-09-28 18:44:51.213911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ff9c7ad6b7a'
down_revision = '138d769e17da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Instructor',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('Reservation',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user'),
    sa.UniqueConstraint('user')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('reserve')
    op.drop_table('users')
    op.drop_table('gym')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('specialty', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('name', name='users_name_key')
    )
    op.create_table('reserve',
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.UniqueConstraint('user', name='reserve_user_key')
    )
    op.drop_table('User')
    op.drop_table('Reservation')
    op.drop_table('Instructor')
    # ### end Alembic commands ###
