"""empty message

Revision ID: 458bafd56829
Revises: 7ccd4385c57f
Create Date: 2023-11-16 20:00:46.952685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '458bafd56829'
down_revision = '7ccd4385c57f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.drop_constraint('instructors_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.create_unique_constraint('instructors_name_key', ['name'])

    # ### end Alembic commands ###
