"""empty message

Revision ID: 9508dc500389
Revises: c7a04c5d7d6b
Create Date: 2023-11-03 18:05:09.406781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9508dc500389'
down_revision = 'c7a04c5d7d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Classes', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
