"""empty message

Revision ID: bc878a2ddbac
Revises: eb219aa5cdbd
Create Date: 2023-11-09 19:23:55.622641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc878a2ddbac'
down_revision = 'eb219aa5cdbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Reservation', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Reservation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('roles')
    # ### end Alembic commands ###
