"""empty message

Revision ID: c7a04c5d7d6b
Revises: 2ff9c7ad6b7a
Create Date: 2023-09-28 18:46:00.683716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a04c5d7d6b'
down_revision = '2ff9c7ad6b7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Reservation', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Reservation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
