"""empty message

Revision ID: e21f068a44ce
Revises: 
Create Date: 2023-09-15 19:50:34.859088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e21f068a44ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fitnessClass',
    sa.Column('_FitnessClass__name', sa.String(length=80), nullable=False),
    sa.Column('_FitnessClass__instructor', sa.String(length=120), nullable=True),
    sa.Column('_FitnessClass__schedule', sa.DateTime(), nullable=True),
    sa.Column('_FitnessClass__maxCapacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('_FitnessClass__name'),
    sa.UniqueConstraint('_FitnessClass__instructor'),
    sa.UniqueConstraint('_FitnessClass__maxCapacity')
    )
    op.create_table('gym',
    sa.Column('_Gym__name', sa.String(length=120), nullable=False),
    sa.Column('_Gym__location', sa.String(length=120), nullable=True),
    sa.Column('_Gym__offeredClasses', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('_Gym__name'),
    sa.UniqueConstraint('_Gym__location'),
    sa.UniqueConstraint('_Gym__offeredClasses')
    )
    op.create_table('reserve',
    sa.Column('_Reserve__user', sa.Integer(), nullable=False),
    sa.Column('_Reserve__date', sa.DateTime(), nullable=True),
    sa.Column('_Reserve__schedule', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('_Reserve__user'),
    sa.UniqueConstraint('_Reserve__user')
    )
    op.create_table('trainingType',
    sa.Column('_TrainingType__name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('_TrainingType__name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('trainingType')
    op.drop_table('reserve')
    op.drop_table('gym')
    op.drop_table('fitnessClass')
    # ### end Alembic commands ###
