from .user_repository import UserRepository
from .instructor_repository import InstructorRepository
from .gym_class_repository import GymClassRepository
from .booking_repository import BookingRepository
